# Generated by Django 4.2.13 on 2024-06-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancetransfermodel',
            old_name='timestamp',
            new_name='data_timte',
        ),
        migrations.RemoveField(
            model_name='balancetransfermodel',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='balancetransfermodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancetransfermodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transfer', to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='balancetransfermodel',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
